import {
  FaLeaf,
  FaAppleAlt,
  FaDrumstickBite,
  FaPepperHot,
  FaCheese,
  FaBreadSlice,
  FaSeedling,
  FaBoxOpen,
} from 'react-icons/fa';

export const ingredientsByCategory = {
  Veggies: [
    'Spinach',
    'Water Spinach',
    'Carrot',
    'Tomato',
    'Broccoli',
    'Green Beans',
    'Mustard Greens',
    'Cabbage',
    'Eggplant',
    'Lettuce',
    'Cucumber',
    'Scallion',
  ],
  Fruits: [
    'Banana',
    'Apple',
    'Orange',
    'Mango',
    'Papaya',
    'Watermelon',
    'Melon',
    'Avocado',
    'Grape',
    'Pineapple',
    'Strawberry',
    'Lemon',
  ],
  Proteins: [
    'Chicken',
    'Egg',
    'Beef',
    'Fish',
    'Tofu',
    'Tempeh',
    'Shrimp',
    'Squid',
    'Sausage',
    'Meatball',
    'Mutton',
    'Duck',
  ],
  Spices: [
    'Shallot',
    'Garlic',
    'Red Chili',
    "Bird's Eye Chili",
    'Ginger',
    'Turmeric',
    'Coriander',
    'Black Pepper',
    'Galangal',
    'Lemongrass',
    'Salt',
    'Sugar',
  ],
  Dairy: [
    'UHT Milk',
    'Cheddar Cheese',
    'Butter',
    'Yogurt',
    'Condensed Milk',
    'Mozzarella Cheese',
    'Milk Powder',
    'Heavy Cream',
    'Cream Cheese',
    'Evaporated Milk',
    'Margarine',
    'Ice Cream',
  ],
  Carbs: [
    'White Rice',
    'White Bread',
    'Potato',
    'Egg Noodles',
    'Pasta',
    'Wheat Flour',
    'Rice Flour',
    'Tapioca Flour',
    'Rice Vermicelli',
    'Oats',
    'Sweet Potato',
    'Corn',
  ],
  Nuts: [
    'Peanut',
    'Cashew',
    'Mung Bean',
    'Red Bean',
    'Soybean',
    'Almond',
    'Edamame',
    'Walnut',
    'Pea',
    'Sesame Seed',
    'Chia Seed',
    'Hazelnut',
  ],
  Others: [
    'Cooking Oil',
    'Sweet Soy Sauce',
    'Chili Sauce',
    'Ketchup',
    'Oyster Sauce',
    'Bouillon Powder',
    'Coconut Milk',
    'Vinegar',
    'Mayonnaise',
    'Shrimp Paste',
    'Soy Sauce',
    'Sesame Oil',
  ],
};

export const categories = [
  { name: 'Veggies', icon: <FaLeaf className='text-green-600' /> },
  { name: 'Fruits', icon: <FaAppleAlt className='text-red-500' /> },
  { name: 'Proteins', icon: <FaDrumstickBite className='text-amber-600' /> },
  { name: 'Spices', icon: <FaPepperHot className='text-orange-500' /> },
  { name: 'Dairy', icon: <FaCheese className='text-yellow-500' /> },
  { name: 'Carbs', icon: <FaBreadSlice className='text-amber-700' /> },
  { name: 'Nuts', icon: <FaSeedling className='text-amber-800' /> },
  { name: 'Others', icon: <FaBoxOpen className='text-gray-500' /> },
];
